
version: '3.3'

services:
   pg1:
     image: postgres:11-alpine
     container_name: pg1
     restart: always
     ports:
       - "5432:5432"
     environment:
       POSTGRES_USER: 'user1'
       POSTGRES_PASSWORD: 'password1'
       POSTGRES_DB: 'blog'
       PGDATA: '/var/lib/postgresql/data/pdata/volume'
     volumes:
       - /tmp/blog/pgdata:/var/lib/postgresql/data/pdata
   cache:
     image: redis:5.0.2-alpine
     container_name: cache
     restart: always
     ports:
        - "6379:6379"
   blobs:
     image: minio/minio:latest
     container_name: blobs
     restart: always
     ports:
        - "9000:9000"
     environment:
        MINIO_ACCESS_KEY: 'abc'
        MINIO_SECRET_KEY: 'abc123def'
    volumes:
        - /tmp/blog/blobs:/data/cache
    command: server --config-dir /data cache
   adminer:
      image: adminer
      container_name: adminer
      restart: always
      ports:
         - "8080:8080"
      depends_on:
       - pg1