
version: '3.3'

services:
   db1:
     image: postgres:11-alpine
     container_name: pg1
     restart: always
     ports:
       - "5432:5432"
     environment:
       POSTGRES_USER: 'user1'
       POSTGRES_PASSWORD: 'password1'
       POSTGRES_DB: 'blog'
       PGDATA: '/var/lib/postgresql/data/pdata/volume'
     volumes:
       - /tmp/blog/pgdata:/var/lib/postgresql/data/pdata
    admin:
      image: adminer
      container_name: admin
      restart: always
      ports:
         - "8080:8080"
      depends_on:
       - db